### ISSUE TITLE
xcodebuild support?

### ISSUE THREAD

**Issue by onmyway133** [agens-no/swiff#12]
Thanks for the nifty tool. However, I don't use fastlane, how to make this work with xcodebuild? Something like `xcodebuild ... | swiff`?

**Comment by hfossli** [comment]
Yep! That should be possible. I know xcodebuild is very verbose, but maybe `xcodebuild ... | xcpretty | swiff` could be a beatiful thing?

**Comment by hfossli** [comment]
This project now supports mint so it easy to install and test

**Comment by onmyway133** [comment]
Ah so it parses xcpretty format. It works for me, here is one sample command if anyone's wondering

```
xcodebuild -project MyApp.xcodeproj -scheme "MyApp Staging" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.4,name=iPhone X' | xcpretty | ./swiff
```
