### ISSUE TITLE
Does not allow user input from a prompt command using Fastlane

### ISSUE THREAD

**Issue by mattxdaigle** [agens-no/swiff#18]
In my Fastfile, I have a prompt that allows me to enter a change log. Running the lane with swiff allows the prompt to print to the Terminal window but the build continues without allowing me to enter any text for the change log. Everything works as expected if I run the same lane without swiff.

**Comment by hfossli** [comment]
Thanks for opening this issue. I should probably state this in the readme. I don't know about any workaround to both use `swiff` and run commands in interactive mode at the same time. It should be possible. 

I just tested to see how swiff works with basic commands

Create a file named hello.sh
```sh
#/bin/sh
echo "> hello!"
sleep 0.8
echo "> what's your name?"
read name
echo "> awesome. ${name} is a great name."
echo "i'm lars btw."
sleep 0.8
echo "i'm a human."
```

And then together with swiff
```sh
chmod u+x hello.sh
./hello.sh | swiff
```

You should be able to write input and pipe to swiff at the same time. Are you using fastlane? If you are I suspect they are detecting that you are piping the output and thus turning off interactive prompts.. https://github.com/fastlane/fastlane/blob/f32b007ff45e648b37b6c9c2037ac481f36b7780/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb#L120-L125

**Comment by hfossli** [comment]
I'm not sure if fastlane does "the right thing", maybe? maybe not?
