### ISSUE TITLE
SPM?

### ISSUE THREAD

**Issue by csjones** [agens-no/swiff#5]
Cool tool! Was wondering if this would support Swift Package Manager? I would love to pull this into my development environment with [mint](https://github.com/yonaskolb/Mint).

**Comment by hfossli** [comment]
Yes, you can use it with any tool that outputs multiple lines. I actually haven’t used spm yet, do you have an example of output?

**Comment by csjones** [comment]
Sorry, I meant for installation of swiff, here is the current output:
```
$ mint install agens-no/swiff
🌱  Finding latest version of swiff
🌱  Resolved latest version of swiff to master
🌱  Cloning https://github.com/agens-no/swiff.git master...
Package.swift not found
```

**Comment by hfossli** [comment]
Awww yeah! That should be possible. If you know how and would like to open a pull request that would be great!! 🤩

**Comment by hfossli** [comment]
Fixed! Thanks to @diamantidis!
